### ISSUE TITLE
Problems loading scripts made in NP++

### ISSUE THREAD

**Issue by dexman545** [Ikkyusan1/typeset-buddy#1]
Hello, I'm trying to try out your plugin and have run into a bit of an issue. I try to make a script with Notepad++, encoded in UTF-8, and when I load it into the script is correct counts the pages, but is unable to load them; however, when I copy all of the text from my script into the example script provided, it is able to properly load the files. A solution beyond duplicating and modifying the example script would be appreciated. Thank you.
![image](https://user-images.githubusercontent.com/4873274/40340045-163800e2-5d4b-11e8-8ff9-ae3d8f02ca09.png)

**Comment by Ikkyusan1** [comment]
Hi, thanks for the report.
Off the top of my head here are my suspects :
- your file is encoded UTF-8 "with BOM"
- your file was encoded multiple times
- you're on Windows, so it could be a problem with the line endings
- some funky characters in your script perhaps

I'll look into it.
In the meantime, if you can provide a "faulty" script file, that'd would be great.
Cheers

**Comment by dexman545** [comment]
I am on Windows. I doubled checked that it was without BOM, so I don't think it's that. There are chinese symbols in the script, so that might be it. Here is a script that does not work.
[Broken.txt](https://github.com/Ikkyusan1/typeset-buddy/files/2037467/Broken.txt)

**Comment by Ikkyusan1** [comment]
Ok so, one of my guesses was correct : it the line endings. Only Unix line endings (LF) are properly handled.
I'll see what I can do.

**Comment by Ikkyusan1** [comment]
Should be fixed. I've released a new version. 

Don't hesitate to open a new issue if you find any problem or if you have ideas to improve the extension.

**Comment by dexman545** [comment]
Thank you very much! it works very well!
