### ISSUE TITLE
Script formatting

### ISSUE THREAD

**Issue by Reacien** [Ikkyusan1/typeset-buddy#12]
I have tried multiple different things, but I have no clue how to exactly format my script to make it work with the program.

**Comment by Ikkyusan1** [comment]
You're gonna have to give a lot more info than that if you want to get some help.
What's your setup (OS, Photoshop version)?
What actually didn't work?
Have you checked the [example](https://github.com/Ikkyusan1/typeset-buddy/blob/7b9204e5ec558827cb7e37b5c8cd6bbd9e62565f/example/example_script.txt)? 
What did you try exactly? Can you provide a piece of your script?

**Comment by Reacien** [comment]
I'm so sorry! I totally overlooked the example script! That was precisely what I was looking for. Much appreciated for linking it to me.

**Comment by Ikkyusan1** [comment]
You're welcome. 
Don't hesitate to ask if you've got trouble with the example. I admit it's a bit messy.
