### ISSUE TITLE
Style Scrolling Too Quickly

### ISSUE THREAD

**Issue by dexman545** [Ikkyusan1/typeset-buddy#2]
With a decently long list of styles, scrolling via mouse wheel to look for a style is difficult, as the smallest increment on mouse wheel scrolls through more than one style. Could you possibly have the increment move one style at a time, or slow down the movement?

**Comment by Ikkyusan1** [comment]
I have no control over this, sorry. 
And I have not witnessed such behavior on any PS install I have. I guess it depends on a number of factor such as OS, version of Photoshop, your system wide mouse scroll speed... 

Still, if you're searching for a particular style in your styleset, you can use the "filter styles" text-input to, well, filter the list.
