### ISSUE TITLE
Where the hell have you been, bro?

### ISSUE THREAD

**Issue by thankyou-xx** [Ikkyusan1/typeset-buddy#5]
Batoto is no more, but you can use the same login for vatoto.com so let's talk there.
Thought you died.

**Comment by thankyou-xx** [comment]
Still waiting for those sfx!

**Comment by Ikkyusan1** [comment]
XD
Sorry for having vanished like that. Way too much stuff on my plate.
I see the end of the tunnel, but I still need 2-3 weeks to get there.
Talk to you soon on vatoto.
